version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: book_library_db
    ports:
      - "5432:5432"
    volumes:
      - ~/.docker-conf/torc/db:/var/lib/postgresql/data    
    # command: >
    #       sh -c "sleep 10 && psql -h localhost -p 5432 -U your_username -d book_library_db -a -f /docker-entrypoint-initdb.d/init.sql"      
    
  api:
    image: torc-book-library
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      # ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=book_library_db;Username=your_username;Password=your_password"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api