version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: book_library_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      sh -c "sleep 10 && psql -U your_username -d book_library_db -a -f /docker-entrypoint-initdb.d/init.sql"

  api:
    image: mcr.microsoft.com/dotnet/aspnet:7.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=book_library_db;Username=your_username;Password=your_password"

  frontend:
    image: node:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      REACT_APP_API_URL: "http://api:80"

volumes:
  pgdata:
